on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/package/build
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Setup new Git branch name
        run: |
          echo "BRANCH_NAME=$(date +%s | awk '{print "gha/sync-icon-"$1}')" >> $GITHUB_ENV
      - run: |
          git checkout -b $BRANCH_NAME
      - run: npm install
      - run: npm run icon:sync
      - name: Commit and push
        run: |
          git config user.name icon-bot
          git add -A
          git commit -am "[GHA] sync new icons from Figma"
          git push origin $BRANCH_NAME
      # - name: create pull request
      #   run: |
      #     gh pr create -B main -H $GITHUB_REF --title 'Merge icon update into main' --body 'Created by Github action - merge new icons'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
