on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/package/build
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run icon:sync
