on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/package/build
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: create pull request
        run: gh pr create -B main -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

